ansforge/IG-fhir-medicosocial-suivi-decisions-orientation

input/FHIR/StructureDefinition-esms-document-reference.json

issue #101 
Originally posted by @nriss in https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/pull/49#discussion_r1452508943

fix id (issue #101)

---

input/FHIR/SDOBundleResultatRechercheNotificationESMS.json
input/FHIR/SDOTask.json

Suppression des "coding.display" (issue #102) et correction d'un url

Suppression des "coding.display" (issue #102) et correction d'un url

---

input/pagecontent/downloads.md

ANS-006-98
Suppression des fichiers turtle
Modification du lien des exemples xml

ANS-006-98 - Correction contenu zip downloads erroné

---

input/images/20240129_CDA_SI-ESMS_Decision.xml
input/images/20240129_CDA_SI-ESMS_Evaluation.xml

Modification des xml pour mise en conformité HL7 CDA

ANS-006-98 - Issue #88 - Exemples CDA - Mise à jour des OID (passage en majuscule)

---

input/FHIR/StructureDefinition-esms-document-reference.json

Mise en cohérence de la description du title avec la règle de gestion

ANS-006-98 - issue #116 - ESMSDocument - MAJ description title

---

input/FHIR/SDOBundleResultatRechercheNotificationESMS.json
input/FHIR/SDOTask.json
input/FHIR/StructureDefinition-esms-consent.json

Modification des apostrophes dans les exemples pour être conforme aux NOS
Modification d'un display pour être conforme au N0S
Ajout de l'URL canonique d'une référence

ANS-006-98 - Issue #123 - corrrectif Q/A

---

input/pagecontent/contenu_dossier.md

Suppression du lien vers les templates Art-Decor

issue #129 - Suppression du lien vers Art-Decor

---

input/FHIR/StructureDefinition-esms-document-reference.json
input/FHIR/StructureDefinition-sdo-document-reference.json
input/FHIR/StructureDefinition-sdo-task.json

issue #142 : correctif de cardinalités des slices statutESMS et TypeDroitPrestation
issue #58 : cardinalité min title déplacée sur la ressource SDODocumentReference, héritée sur la ressource ESMSDocumentReference

ANS-006-98 - Reprise - Issue #142 #58 - Correctifs SD SDO Task et DocumentReference

---

input/fsh/instances/exemple-bundle-resultat-recherche-decision-evaluation.fsh
input/fsh/instances/exemple-bundle-resultat-recherche-decision-evaluation_elements.fsh
input/fsh/instances/exemple-esms-document-reference.fsh
input/fsh/instances/exemple-sdo-document-reference.fsh

Creation example exemple-bundle-resultat-recherche-decision-evaluation-elements
* Creation example exemple-bundle-resultat-recherche-decision-evaluation-elements
* Modification des 2 exemples de DocumentReference pour utiliser le slicing via fsh
https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/issue157/ig

ANS-006-115 - issue 157 - Création nouvel exemple Bundle + MAJ des exemples existants

---

input/fsh/CapabilityStatement/ESMSConsommateur.fsh
input/fsh/CapabilityStatement/ESMSProducteur.fsh
input/fsh/CapabilityStatement/SDOGestionnaire.fsh
input/pagecontent/liste_profils.md

* Ajout des CapabilityStatement dans la liste des ressources FHIR via SQL
* Mise à jour des "title" des CapabilityStatement
https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/issues173/ig

ANS-006-115 - issue 173- Ajout des CapabilityStatement dans la liste des ressources FHIR

---

input/images/CDA_SI-ESMS_Decision.xml
input/images/CDA_SI-ESMS_Evaluation.xml
input/pagecontent/contenu_dossier.md

#155  : Suppression du mapping de l'identifiant de document avec la donnée fonctionnelle Decision.idDecision
#178  : Modification du bloc adresse pour positionner les éléments useablePeriod en fin de bloc adresse
#127 : mise à jour des exemples suite à mise à jour du schematron
https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/issue155-MAJCDA/ig

ANS-006-115 - issue 155 - 178 -127 - Corectifs contenuDossier

---

sushi-config.yaml

* [changement 1]
* [changement 2]
* ...
https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/[ajouter_nom_de_la_branche]/ig

Update NOS dependency

---

input/images-source/flux1.plantuml
input/images-source/flux2.plantuml
input/images-source/flux3.plantuml
input/images-source/flux4.plantuml
input/images-source/flux5.plantuml

* Ajout des noms de profil sur diagrammes
https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/171-synthese-flux-ajouter-les-profils-utilisés-sur-les-diagrammes/ig/synthese_flux.html

Ajout des noms de profil sur diagramme

---

input/images/20240124_DiagrammeSequence_Global.drawio

* Ajout du fichier source draw.io
https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/227-annexe-diagramme-de-séquence-b-e-b-corriger-le-flux-14/ig

ANS-006-133- Ajout fichier source draw.io diagramme b-e-b

---

input/pagecontent/st_flux1.md
input/pagecontent/st_flux5.md

* Modification des descriptions des paramètres de recherche de type date pour le flux 1.1 et 5.1
https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/229-format-de-la-date-dernière-recherche-flux-11-et-flux-51/ig

ANS-006-133 - Evolution format parametre last_Updated flux 1.1 et 5.1

---

input/pagecontent/index.md
input/pagecontent/ressource_fhir.md

Réécriture des requêtes SQL pour tenir compte de la nouvelle version de l'IG publisher;
* [changement 1]
* [changement 2]
* ...
https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/253-modifi-des-reqêtes-sqlite-pour-tenir-compte-nouvelle-version-publisher/ig/index.html

modification des reqêtes sqlite pour tenir compte nouvelle version de l'IG publisher

---

input/pagecontent/st_flux1.md
input/pagecontent/st_flux5.md

* Ajout d'un texte explicatif sur la necessité d'échapper le "+" dans le paramètre lastUpdated sur la page 1.1 et 5.1
https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/[ajouter_nom_de_la_branche]/ig

ANS-006-133 - flux - MAJ description paramètre _lastUpdated

---

input/fsh/profiles/SDOTask.fsh

* SDOTask.status fixé à Completed
https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/[ajouter_nom_de_la_branche]/ig

ANS-006-133 - RC - Ajout contrainte Task.status

---

input/pagecontent/securite.md

* fix typo sur la page securite.md
https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/[ajouter_nom_de_la_branche]/ig

ANS-006-133 - Autre ressources - Correction de typo sur la page Sécurité

---

input/fsh/profiles/ESMSConsent.fsh

Consent.Status fixé à Active
* Consent.Status fixé à Active
https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/278-rc---esmsconsent---missing-status-constraint/ig

Consent.Status fixé à Active

---

input/pagecontent/downloads.md

* MAJ Page "Téléchargements et usage"
https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/110-downloads---suivre-la-mise-à-jour-de-lig-modele/ig

MAJ Page "Téléchargements et usage"

---

input/fsh/instances/exemple-sdo-bundle-resultat-recherche-notifications-esms.fsh
input/fsh/instances/exemple-sdo-task.fsh
input/fsh/profiles/SDOTask.fsh
input/pagecontent/correspondance_objet.md

* Suppression de la slice TypdeDroitPrestation dans le profil et les exemples
* Suppression de la ligne DroitPrestation et TypeDroitPrestation dans la mise en correspondance entre objets métiers et ressources FHIR
* ...
https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/265-rc---task---supprimer-le-typedroitprestation/ig

ANS-006-140 - RC Task - suppression du typedroitprestation

---

input/images/CDA_SI-ESMS_Decision.xml
input/pagecontent/contenu_dossier.md

* Ajout de la civilité (facultatif) dans le name du patient
* Mise à jour des contraintes liées à l'INS
* Evolution du type de l'extension numSecuriteSociale et ajout des OID des autorités d'affectation des NIR et NIA utilisés en tant que numéro de sécurité sociale
https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/MAJ_identie_Patient/ig

ANS-006-140 - MAJ de l'identité du patient (contraintes INS)

---

publication-request.json
release-notes.md
sushi-config.yaml

Modifications des fichiers pour publication
* release-note
* sushi-config.yaml 
* publication-request.json
https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/298-preparation-realease-403-ballot/ig

publication de la release 403-ballot

---

input/pagecontent/tests.md

*Mise à jour du nom des validateurs cda dans le fichier tests.md
https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/303-MajNomValidateurs/ig/tests.html

ANS-006-140 - #303 Tests - Mettre à jour le nom des validateurs CDA ESMS

---

input/images/CDA_SI-ESMS_Decision.xml
input/images/CDA_SI-ESMS_Evaluation.xml
input/pagecontent/contenu_dossier.md

* Changement de la card du setID pour le rendre obligatoire
* Mise en place de l'attribut extension obligatoire au niveau du setID pour porter l'ID_Nat_Decision
https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/313-MajSetID/ig/contenu_dossier.html

ANS-006-140 - #313 MAJ setID

---

input/pagecontent/securite.md

Ajouter un lien vers les exigences d'authentification de ViaTrajectoire
https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/221-sécurité---ajouter-les-spécifications-vt/ig

Sécurité - Ajouter les spécifications VT
